### PR TITLE
fix: Partykit handle null connection state 

### PR DESCRIPTION
**Pull request by hassnian**
### Context 

https://github.com/kodadot/nft-gallery/pull/9439

### CODE REVIEW

**Comment by yangwao** [comment]
should I deploy?

**Comment by hassnian** [comment]
> should I deploy?

sure

**Comment by vikiival** [comment]
Yolo

**Comment by yangwao** [comment]
@vikiival has merged but didn't deploy.

@vikiival let us know when it's deployed so we can test

**Comment by vikiival** [comment]
> let us know when it's deployed so we can test

I cannot deploy it since this is not a Cloudflare worker. 
It is bound to @hassnian or someone else account.

```bash
 $ pnpm deploy
 ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace
 ```

**Comment by hassnian** [comment]
> > let us know when it's deployed so we can test
> 
> I cannot deploy it since this is not a Cloudflare worker. It is bound to @hassnian or someone else account.
> 
> ```shell
>  $ pnpm deploy
>  ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace
> ```
> 
> Moreover It is missing proper readme :)

will add ASAP , meanwhile 

https://github.com/kodadot/workers/pull/251#issuecomment-1946039814

https://docs.partykit.io/guides/deploy-to-cloudflare/


iirc you have to `npx partykit login` first 

then run this command 

`````

CLOUDFLARE_ACCOUNT_ID=<your account id> CLOUDFLARE_API_TOKEN=<your api token> npx partykit deploy --domain partykit.domain.com
`````

**Comment by yangwao** [comment]
```
Deploying...
Deployed ./src/index.ts to https://partykit.kodadot.workers.dev
```

**Pull request merged**
