### PR TITLE
feat: cloudflare streams

### LINKED ISSUE #186: Implement Cloudflare Stream (?)
oohh, thanks for the report. I just got some idea

currently, we already optimize images with https://developers.cloudflare.com/images/cloudflare-images/
for video, maybe we can use this https://developers.cloudflare.com/stream/

_Originally posted by @preschian in https://github.com/kodadot/workers/issues/185#issuecomment-1770938132_

### PR DESCRIPTION
**Pull request by preschian**
Fix #186

### CODE REVIEW

**Comment by preschian** [comment]
Hi @kodadot/internal-dev, I will test this PR to Canary. Let me know if you find a problem related to the video.

**Comment by preschian** [comment]
Ok, it now seems to work on iOS: https://deploy-preview-8171--koda-canary.netlify.app/ahp/gallery/10-26.

https://github.com/kodadot/nft-gallery/pull/8171

### Need Confirmation:
How about the pricing? Should we go or not? cc @yangwao. there is `scheduledDeletion` in the API. So, we can save up the storage by auto deletion unused video.

Screenshot 2024-01-04 at 10 15 57 AM

### Consequences:
- processing video from ipfs to cf-stream takes time. Ref: https://developers.cloudflare.com/stream/get-started/#step-2-wait-until-the-video-is-ready-to-stream

Workaround: add some placeholder text on iOS while the video is still processing. There is no problem on the other platform. It can fallback to the worker video.

### Area of improvement:

With cf-stream, we get:
- HLS -> https://customer-sv7iz1h2svh2ak10.cloudflarestream.com/b461eebc3c3e490c584cc07cf3455148/manifest/video.m3u8
- Dash -> https://customer-sv7iz1h2svh2ak10.cloudflarestream.com/b461eebc3c3e490c584cc07cf3455148/manifest/video.mpd
- MP4 -> https://customer-sv7iz1h2svh2ak10.cloudflarestream.com/b461eebc3c3e490c584cc07cf3455148/downloads/default.mp4
- built-in player -> https://customer-sv7iz1h2svh2ak10.cloudflarestream.com/b461eebc3c3e490c584cc07cf3455148/watch
- thumbnail -> https://customer-sv7iz1h2svh2ak10.cloudflarestream.com/b461eebc3c3e490c584cc07cf3455148/thumbnails/thumbnail.jpg

in https://github.com/kodadot/nft-gallery/pull/8171, I just changed the mp4 file with cf-stream. Built-in player/HLS/Dash is really helpful for users with low-speed networks because the user can select the video quality (like watching YouTube videos).

image

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
Let's test.

> How about the pricing? Should we go or not?

we can give it a shot. Worst case we can revert

**Comment by preschian** [comment]
> we can give it a shot. Worst case we can revert

ah, good idea 👍🏻



> Let's test.

ok, will merge this. and little adjustment on nft-gallery

**Pull request merged**
