### PR TITLE
feat: PartyKit integration

### PR DESCRIPTION
**Pull request by hassnian**
from issue https://github.com/kodadot/nft-gallery/issues/9360

### CODE REVIEW

**Comment by yangwao** [comment]
good for me

**Comment by yangwao** [comment]
cc @preschian can we deploy it?

**Comment by hassnian** [comment]
> cc @preschian can we deploy it?

for cloudflare

https://docs.partykit.io/guides/deploy-to-cloudflare/

otherwise 

https://docs.partykit.io/guides/deploying-your-partykit-server/

**Comment by yangwao** [comment]
> for cloudflare

thanks, I've created api token 

-JzQMS3Mj07P0HO82wV6v9qJTrfL_8gYdsYhhr34

**Comment by yangwao** [comment]
okay let me try lol

**Comment by yangwao** [comment]
> We're provisioning the partykit.kodadot.workers.dev domain. This can take up to 2 minutes. Hold tight!

**Comment by yangwao** [comment]
> Deployed ./src/index.ts to https://partykit.kodadot.workers.dev

**Pull request merged**
