### PR TITLE
🔧 ssr opengraph prerender routes

### LINKED ISSUE #79: simplify ssr-opengraph routes
- https://github.com/kodadot/workers/actions/runs/4713419090 deployed `ssr-opengraph-beta` 

btw, if these triggers would be 

`*.kodadot.xyz/ksm/*` would not work or it would throw errors on some other routes than `u`,`collection`,`gallery` ? Just thinking simplifying it per-chain

image

_Originally posted by @yangwao in https://github.com/kodadot/workers/issues/44#issuecomment-1510375069_

### LINKED ISSUE #104: open-graph for statemine
https://github.com/kodadot/nft-gallery/issues/6252#issuecomment-1594576607

### PR DESCRIPTION
**Pull request by roiLeo**
YOLO

- Close #79 
- Close #104

### CODE REVIEW

**Comment by vikiival** [comment]
approved by @yangwao 

Screenshot 2023-06-21 at 14 29 22

**Comment by roiLeo** [comment]
🙏 lmk if it's working as excepted

**Comment by vikiival** [comment]
https://github.com/kodadot/workers/actions/runs/5334084162

**Comment by roiLeo** [comment]
`cd: ssr-opengraph-beta: No such file or directory` I think deploy workflow need some tweak

**Comment by vikiival** [comment]
maybe preschian would know?

**Comment by preschian** [comment]
> cd: ssr-opengraph-beta: No such file or directory

oh, we already unify ssr-opengraph-beta to ssr-opengraph. just select the environment

**Comment by preschian** [comment]
seems like the wildcard is not supported https://github.com/kodadot/workers/actions/runs/5334994550/jobs/9667579098

```
Route pattern may only contain wildcards at the beginning of the hostname and the end of the path: *.kodadot.xyz/*/gallery/* [code: 10022]
```

**Comment by roiLeo** [comment]
> seems like the wildcard is not supported https://github.com/kodadot/workers/actions/runs/5334994550/jobs/9667579098

I'll make the changes if you want

**Comment by roiLeo** [comment]
https://github.com/kodadot/workers/issues/104#issuecomment-1602248339

**Pull request merged**
