### PR TITLE
feat: og for koda.art

### PR DESCRIPTION
**Pull request by preschian**

### CODE REVIEW

**Comment by vikiival** [comment]
and base?

**Comment by preschian** [comment]
not sure why can't deploy this worker. probably due to breaking changes from wrangler v2 to v3

```
  ✘ [ERROR] A request to the Cloudflare API (/zones/9bcf5f14dec09f43ca97cf258bef8340/workers/routes) failed.
  
    Authentication error [code: 10000]
```

**Comment by preschian** [comment]
It seems like the token expired or was misconfigured. Need to update it. 

```
🔓 To see token permissions visit https://dash.cloudflare.com/profile/api-tokens
```

And update the GitHub secrets
```
apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```

I don't have access for both of them. cc @vikiival

**Comment by vikiival** [comment]
Updated

**Comment by preschian** [comment]
> Updated

Now the error is: 

```
👋 You are logged in with an API Token. Unable to retrieve email for this user. Are you missing the `User->User Details->Read` permission?
```

**Comment by preschian** [comment]
> > Updated
> 
> Now the error is:
> 
> ```
> 👋 You are logged in with an API Token. Unable to retrieve email for this user. Are you missing the `User->User Details->Read` permission?
> ```

cc @vikiival

**Comment by vikiival** [comment]
image

**Comment by preschian** [comment]
@vikiival still same error

**Comment by vikiival** [comment]
How can I test it?

**Comment by vikiival** [comment]
> I don't have access for both of them. cc @vikiival

You have access to both

**Comment by preschian** [comment]
> You have access to both

done, updated the token. continue here: https://github.com/kodadot/workers/pull/301

**Pull request closed without merging**
