### PR TITLE
Collective-worker

### PR DESCRIPTION
**Pull request by daiagi**
@kodadot/internal-dev 
currently stuck with this error:

### EDIT

false alarm - found solution

`
FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly.instantiate(): Wasm code generation disallowed by embedder`

which is related to the attmpt to init api in /utils/api

any ideas / suggestion how to move forward?

image

### CODE REVIEW

**Comment by daiagi** [comment]
nvm
seems i have found the solution

image

**Comment by vikiival** [comment]
Wanted to code that over weekend but can do other thingies.

### In general

There is already a full example for worker like this: in kodadot/private-workers

1. you are missing a query builder - i am using kysely, it works fine 
2. you are missing types for the database - it is done via kysely-typegen
3. you do not need polkadot api - i have written a whole signer - `@polkadot/api` does not work on the production `workerd` runtime - I have trying to make it work since Q3 2023. - I can finish this part
4. This worker should be part of kodadot/private-workers
5. If anything is unclear feel free to DM me

**Comment by vikiival** [comment]
Closing as this should be part of other repository.

**Comment by daiagi** [comment]
> Wanted to code that over weekend but can do other thingies.

ok. sounds like you got it already and don't need me on this

**Comment by vikiival** [comment]
> ok. sounds like you got it already and don't need me on this

No, feel free, I would rather guide ^-^

**Comment by vikiival** [comment]
@daiagi you made already a great job!
If you got stuck on something (typegen) or something lmk

**Comment by daiagi** [comment]
sure I'll continue
Q:
1. to clarfiy, the API that should be called in `/collectives` is `mint` an nft. correct?
2. >you do not need polkadot API 

that good. How to mint?
do I use same as in waifu worker?
const BASE_URL = 'https://waifu.deno.dev'

**Comment by vikiival** [comment]
I can make the the minting stuff. Just make a placeholder function that will return hash.

**Pull request closed without merging**
