### PR TITLE
feat: add collections farcaster frame

### PR DESCRIPTION
**Pull request by Complexlity**

### CODE REVIEW

**Review by yangwao — APPROVED** [review]

**Comment by yangwao** [comment]
Can we have an official deployment of this code, please, @preschian ? 🙏

**Comment by preschian** [comment]
> Can we have an official deployment of this code, please, @preschian ? 🙏

As long the project uses Cloudflare worker and javascript should be able to deploy through GitHub actions

Let me test

**Comment by preschian** [comment]
oh, missing some entry points https://github.com/kodadot/workers/actions/runs/8466423355/job/23195151609

will check later

**Comment by yangwao** [comment]
no rush, we are already have one working from Complexlity so using then one hopefully won't put it down upcoming month, jk I believe next week we will have it up :)

**Pull request merged**
