### PR TITLE
feat: support sub path ipfs

### PR DESCRIPTION
**Pull request by preschian**
related https://github.com/kodadot/nft-gallery/issues/4872

### CODE REVIEW

**Comment by vikiival** [comment]
@preschian 
```
Total Upload: 42.26 KiB / gzip: 10.26 KiB
Uploaded image-beta (2.93 sec)
Published image-beta (1.57 sec)
  https://image-beta.kodadot.workers.dev
Current Deployment ID: 60d99d20-f6c0-4ff1-a352-a0e0af5d80f3
```

**Comment by vikiival** [comment]
Actually, metadata loading takes a while these days

**Comment by vikiival** [comment]
Anything from valentine coletion /bsx/collection/14022023

**Comment by vikiival** [comment]
Yeah but nft-storage fails when you pass to many requests

**Comment by yangwao** [comment]
Can we use https://nftstorage.link/ ?

**Comment by vikiival** [comment]
No, because it throws 429 after 10 requests

**Comment by vikiival** [comment]
So let's merge this?

**Review by vikiival — APPROVED** [review]

**Pull request merged**
