### PR TITLE
feat: add image gateway (cloudflare images + r2)

### PR DESCRIPTION
**Pull request by preschian**
- [x] closes https://github.com/kodadot/nft-gallery/issues/4587
- [x] closes https://github.com/kodadot/workers/issues/17

### CODE REVIEW

**Comment by yangwao** [comment]
> cache only works on custom domains. add custom domains after deploying the workers. (under trigger tabs)

at first need to deploy under our account? as I don't see it there

was thinking about some convention, like `w.kodadot.xyz` could be base prefix? 
so in this case `image.w.kodadot.xyz` ?

cc @vikiival

**Comment by yangwao** [comment]
> need to change these values

are there any tokens I should add to netlify/cf-pages deploy to work this?

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
@preschian do I need to change this ? 

```
[[r2_buckets]]
bucket_name = 'r2-assets'
preview_bucket_name = 'test-ipfs-assets'
```

@yangwao updated in [2410b11](https://github.com/kodadot/workers/pull/18/commits/2410b1152209ea0ac66deea1c0b1ba7c3cc88086)

**Comment by vikiival** [comment]
> 🌀 Creating the secret for the Worker "image"
> ✨ Success! Uploaded secret IMAGE_API_TOKEN

**Comment by vikiival** [comment]
> Published image (6.39 sec)
>  https://image.kodadot.workers.dev

**Comment by vikiival** [comment]
@preschian ill do that ☺️

**Comment by vikiival** [comment]
kodadot/nft-gallery#4596

**Comment by yangwao** [comment]
If I get it right @preschian ? 

It might require time to initialize - https://image.w.kodadot.xyz/

image

**Comment by yangwao** [comment]
also bundled is that edge caching maybe? 

image

**Comment by yangwao** [comment]
> wanna use a subdomain

it's active already - [image.w.kodadot.xyz](https://image.w.kodadot.xyz/)

image

**Pull request merged**
