### PR TITLE
fix: support ipfs full path

### PR DESCRIPTION
**Pull request by preschian**
Context

- [x] closes https://github.com/kodadot/nft-gallery/issues/4872

Screenshot 2023-01-31 at 20 03 15

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Please rename ipfsFile to path

**Comment by vikiival** [comment]
Also @preschian if you find a way how to fix the action i would be really happy

**Comment by yangwao** [comment]
> make sure to add `CLOUDFLARE_API_TOKEN` in GitHub secrets.

added

**Comment by yangwao** [comment]
image


image


uh sexi

**Pull request merged**
