### PR TITLE
fix: koda logo

### PR DESCRIPTION
**Pull request by Jarsen136**
## Context

1. _describe why do we need this change?_
https://github.com/kodadot/nft-gallery/issues/10939

2. _what is the problem?_
the logo is old: https://raw.githubusercontent.com/kodadot/kodadot-presskit/main/pre-v4/png/KodalightV4.png

2. _how did you solve the problem?_

upload the new logo and use its URL from github

## Ref

- [x] References https://github.com/kodadot/nft-gallery/issues/10939

## PR Type

- [x] Bugfix

### CODE REVIEW

**Comment by Jarsen136** [comment]
failed test https://github.com/kodadot/workers/pull/331

**Comment by vikiival** [comment]
Test is failing

Screenshot 2024-09-09 at 18 01 17

**Comment by vikiival** [comment]
pls update the branch

**Comment by Jarsen136** [comment]
> pls update the branch

done

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
Pls deploy

**Comment by Jarsen136** [comment]
deployed

image

**Pull request merged**
