### PR TITLE
Capture-screenshot-worker

### LINKED ISSUE #169: Capture service
### Context

When user makes and iteration (new art) there is no way on frontend to take the static image. 

The idea is to create some headless browser, capture the screen and return the image.
Ideally use `hono`.

### Original

When a generative art is renered we need to create a medata for the nft namely: `image` and `thumbnail`

This is on generative platforms like fxhash done via [Capture Settings](https://www.fxhash.xyz/doc/artist/project-settings#capture-settings)

### PR DESCRIPTION
**Pull request by daiagi**
-[x] closes  #169

@vikiival 
this is quite basic and I am not sure if it even has any value as my ability to test was limited
due to

image

https://github.com/cloudflare/workers-sdk/issues/3433

in theory, it should take a body of  
```json
{
"url": "http://example.com"
}
```

and return a screenshot of it (cached)

### CODE REVIEW

**Comment by vikiival** [comment]
Hey thanks for the quick hack!

as promised I will test it

**Comment by vikiival** [comment]
Requested the access

```
npx wrangler dev --remote
```

```yml
- Browser:
  - Name: MYBROWSER
- http://0.0.0.0:55580
- http://127.0.0.1:55580
- http://192.168.0.52:55580
```

```
Total Upload: 599.05 KiB / gzip: 106.04 KiB
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API
```

```js
  {
    text: 'A request to the Cloudflare API
  (/accounts/b3f9fdfd827152316d080a5ddee59915/workers/scripts/screenshot/edge-preview) failed.',
    notes: [
      {
        text: 'workers.api.error.no_access_to_browser_worker [code: 10088]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10088
  }
```

**Comment by vikiival** [comment]
❤️ 

Screenshot 2023-10-30 at 14 18 00

**Comment by daiagi** [comment]
really?!
i'm shocked that it works
couldn't do even the most basic of testing before handing it over lol

**Comment by vikiival** [comment]
I made some changes so we have v0 version

Screenshot 2023-10-30 at 15 17 16

Screenshot 2023-10-30 at 14 34 21

**Comment by vikiival** [comment]
Thanks @daiagi for setup!

**Pull request merged**
