### PR TITLE
feat: prerender blog

### PR DESCRIPTION
**Pull request by preschian**
- Related https://github.com/kodadot/nft-gallery/issues/6419

### CODE REVIEW

**Comment by preschian** [comment]
deployed on canary and beta

image

image

**Comment by preschian** [comment]
for production wait after this issue resolved https://github.com/kodadot/nft-gallery/issues/6470

**Comment by yangwao** [comment]
actually drops did not work either tbh but we can try now?

**Comment by yangwao** [comment]
> deployed on canary and beta

canary and beta worked even then.

**Comment by preschian** [comment]
> actually drops did not work either tbh but we can try now?

deployed on for production env https://github.com/kodadot/workers/actions/runs/5677133657/job/15384945882

but I can't test it

image

**Pull request merged**
