### PR TITLE
🔧 ogi round price

### PR DESCRIPTION
**Pull request by roiLeo**
Capture d’écran 2023-11-15 à 9 05 40 AM
Capture d’écran 2023-11-15 à 9 04 11 AM

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by roiLeo** [comment]
@preschian imo we should change some part of text "price (usd)" "price" I find it a bit repetitive

**Comment by preschian** [comment]
> @preschian imo we should change some part of text "price (usd)" "price" I find it a bit repetitive

sure, lets replace it with something better

**Comment by yangwao** [comment]
> text "price (usd)" "price" I find it a bit repetitive

I think if we drop it it's oke

**Comment by roiLeo** [comment]
> I think if we drop it it's oke, less is more

drop what? which one?  I'm looking to remove `[Beta]` from network too since there's no point to having it

**Comment by yangwao** [comment]
> drop what?

price

i.e. if you look on GH cards they don't explain this is "date" for example. 

image

when someone see $, it's pretty self-explanatory tbh.

I would even vote to drop DOT as we want to be focused on "consumer-friendly" side

**Comment by roiLeo** [comment]
Something like this?
og

> when someone see $, it's pretty self-explanatory tbh.
> 
> I would even vote to drop DOT as we want to be focused on "consumer-friendly" side

I'd like to keep DOT value if possible, I know you are trying to simplify user experience but I see some advantages to keep it

**Comment by yangwao** [comment]
> keep DOT value if possible

maybe could be under each other? but I think this is good for now, it is still 200% improvement what we had. Only one idea if we would put logo on left upper corner too? Or bottom right 
I perceive it as standard recognition in left upper, yet in bottom right it would be unified tho

**Pull request merged**
