### PR TITLE
feat: render original content

### PR DESCRIPTION
**Pull request by preschian**
http://localhost:8787/ipfs/QmdWuMnTtoA53i23hokJmqSoQBCDRvXrjY4DPTTPppAcEv?original=true

- Related https://github.com/kodadot/nft-gallery/issues/6638

### CODE REVIEW

**Comment by preschian** [comment]
@vikiival @roiLeo, up up. any feedback or concerns maybe?

**Review by vikiival — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
so when we'll need to donwload original image we juste have to call ipfs link with `?original=true`?

**Comment by vikiival** [comment]
> so when we'll need to donwload original image we juste have to call ipfs link with `?original=true`?

As I understand then Yes

**Comment by preschian** [comment]
correct, it will skip redirecting to cf-images

**Pull request merged**
